# Generated by Django 3.0 on 2019-12-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.CharField(default='', max_length=255)),
                ('nama', models.CharField(default='', max_length=255)),
                ('harga', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
