# Generated by Django 3.0 on 2019-12-12 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.TextField(default='')),
                ('produk_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Produk')),
            ],
        ),
    ]
